name: Frontend CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'frontend/**'

env:
  NODE_VERSION: 22
  WORKING_DIRECTORY: frontend

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: |
          cd ${{ env.WORKING_DIRECTORY }}
          yarn install --frozen-lockfile --ignore-scripts
      - name: Run format check
        run: |
          cd ${{ env.WORKING_DIRECTORY }}
          yarn format
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: |
          cd ${{ env.WORKING_DIRECTORY }}
          yarn install --frozen-lockfile --ignore-scripts
      - name: Run lint check
        run: |
          cd ${{ env.WORKING_DIRECTORY }}
          yarn lint
